# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kfrnbbKEEMVYrwM-pb-Rv6uqrsKvLPTJ
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from imblearn.over_sampling import SMOTE
from scipy.stats import zscore
import numpy as np

crop = pd.read_csv('/content/Crop_recommendation.csv')

crop.info()

crop.shape

crop['label'].unique()

crop.describe()

crop.isnull().sum()

mean_values = crop.mean(numeric_only=True)
print("Mean values:\n", mean_values)
print('==============================')
median_values = crop.median(numeric_only=True)
print("Median values:\n", median_values)
print('==============================')
max_values = crop.max(numeric_only=True)
print("Max values:\n", max_values)
print('==============================')
min_values = crop.min(numeric_only=True)
print("Min values:\n", min_values)
print('==============================')
std_values = crop.std(numeric_only=True)
print("Std values:\n", std_values)

crop =crop.dropna()

crop.describe(include='object')

import pandas as pd

df = pd.read_csv("/content/Crop_recommendation.csv")
print(df.dtypes)
print('===================================')
crop_counts = df['label'].value_counts()
print(crop_counts)

X = df.drop('label', axis=1)   # all input features
y = df['label']

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)

print(le.classes_)

from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
crop['label'] = Le.fit_transform(crop['label'])
print(crop)

crop.head()

#split the data to train and test
crop.head()
x = crop[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]
y = crop['label']

X.head()

y.head()

for i ,crop in enumerate(le.classes_):
 print(i, "->", crop)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000
)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))



cm = confusion_matrix(y_test, y_pred)
print(cm)

import pickle
with open('crop_model.pkl','wb') as f:
  pickle.dump(model,f)

with open('scaler.pkl','wb') as f:
  pickle.dump(scaler,f)

with open('label_encoder.pkl','wb') as f:
  pickle.dump(le,f)

